swagger: "2.0"
info:
  description: "Simple Bank Service Rest API"
  version: "1.0.0"
  title: "Bank Service Rest API"
  contact:
    email: "dominikcebula@gmail.com"
paths:
  /:
    get:
      summary: "Index Action showing that service is up"
      responses:
        200:
          description: "Service is up"
          schema:
            $ref: '#/definitions/HealthCheckResponse'

  /accounts/list:
    get:
      summary: "List all accounts in the system"
      responses:
        200:
          description: "Accounts list"
          schema:
            $ref: '#/definitions/ListAccountsResponse'

  /accounts/create:
    post:
      summary: "Create new account"
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/AccountOpenRequest'
      responses:
        200:
          description: "Created Account details"
          schema:
            $ref: '#/definitions/AccountOpenResponse'

  /transfer:
    post:
      summary: "Transfer money between accounts"
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/TransferMoneyRequest'
      responses:
        200:
          description: "Transferred money operation result"
          schema:
            $ref: '#/definitions/TransferMoneyResponse'

definitions:
  Money:
    type: "number"
    format: "float"
  AccountId:
    type: "string"
  Account:
    type: "object"
    properties:
      accountId:
        $ref: '#/definitions/AccountId'
      balance:
        $ref: '#/definitions/Money'
  Accounts:
    type: object
    properties:
      accounts:
        type: "array"
        items:
          $ref: '#/definitions/Account'
      totalDeposit:
        $ref: '#/definitions/Money'

  HealthCheckResponse:
    type: "object"
    properties:
      status:
        type: "string"
        enum:
          - "up"

  ListAccountsResponse:
    type: object
    properties:
      status:
        $ref: '#/definitions/ApiResponse'
      accounts:
        $ref: '#/definitions/Accounts'

  AccountOpenRequest:
    type: object
    properties:
      initialDeposit:
        $ref: '#/definitions/Money'
  AccountOpenResponse:
    type: "object"
    properties:
      status:
        $ref: '#/definitions/ApiResponse'
      account:
        $ref: '#/definitions/Account'

  TransferMoneyRequest:
    type: "object"
    properties:
      from:
        $ref: '#/definitions/AccountId'
      to:
        $ref: '#/definitions/AccountId'
      amount:
        $ref: '#/definitions/Money'
  TransferMoneyResponse:
    properties:
      status:
        $ref: '#/definitions/ApiResponse'
      from:
        $ref: '#/definitions/AccountId'
      to:
        $ref: '#/definitions/AccountId'
      amount:
        $ref: '#/definitions/Money'

  ApiCode:
    type: "string"
    enum:
      - FAILED
      - ACCOUNT_OPENED
      - ACCOUNTS_LISTED
      - MONEY_TRANSFERED
  ApiResponse:
    type: "object"
    properties:
      code:
        $ref: '#/definitions/ApiCode'
  ApiErrorResponse:
    type: "object"
    allOf:
      - $ref: '#/definitions/ApiResponse'
      - properties:
          message:
            type: string