openapi: "3.0.0"
info:
  description: "Simple Bank Service Rest API"
  version: "1.0.0"
  title: "Bank Service Rest API"
  contact:
    email: "dominikcebula@gmail.com"
  license:
    name: MIT
paths:
  /:
    get:
      summary: "Index Action showing that service is up"
      responses:
        '200':
          description: "Service is up"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthCheckResponse'

  /accounts/list:
    get:
      summary: "List all accounts in the system"
      responses:
        '200':
          description: "Accounts list"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListAccountsResponse'
        '400':
          description: "Validation Error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        '500':
          description: "Internal Request Processing Error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'

  /accounts/create:
    post:
      summary: "Create new account"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountCreateRequest'
      responses:
        '200':
          description: "Created Account details"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountCreateResponse'
        '400':
          description: "Validation Error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        '500':
          description: "Internal Request Processing Error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'

  /transfer:
    post:
      summary: "Transfer money between accounts"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MoneyTransfer'
      responses:
        '200':
          description: "Transferred money operation result"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferMoneyResponse'
        '400':
          description: "Validation Error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        '500':
          description: "Internal Request Processing Error"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'

components:
  schemas:
    Money:
      type: "number"
      format: "float"
      minimum: 0
    AccountId:
      type: "string"
      pattern: "^[0-9]{16}$"
    Account:
      type: "object"
      required:
        - accountId
        - balance
      properties:
        accountId:
          $ref: '#/components/schemas/AccountId'
        balance:
          $ref: '#/components/schemas/Money'
    Accounts:
      type: object
      required:
        - accounts
        - totalDeposit
      properties:
        accounts:
          type: "array"
          items:
            $ref: '#/components/schemas/Account'
        totalDeposit:
          $ref: '#/components/schemas/Money'
    MoneyTransfer:
      type: object
      required:
        - from
        - to
        - amount
      properties:
        from:
          $ref: '#/components/schemas/AccountId'
        to:
          $ref: '#/components/schemas/AccountId'
        amount:
          $ref: '#/components/schemas/Money'

    HealthCheckResponse:
      type: "object"
      required:
        - status
      properties:
        status:
          type: "string"
          enum:
            - "up"

    ListAccountsResponse:
      type: object
      required:
        - status
        - accounts
      properties:
        status:
          $ref: '#/components/schemas/ApiResponse'
        accounts:
          $ref: '#/components/schemas/Accounts'

    AccountCreateRequest:
      type: object
      required:
        - initialDeposit
      properties:
        initialDeposit:
          $ref: '#/components/schemas/Money'
    AccountCreateResponse:
      type: "object"
      required:
        - status
        - account
      properties:
        status:
          $ref: '#/components/schemas/ApiResponse'
        account:
          $ref: '#/components/schemas/Account'

    TransferMoneyResponse:
      required:
        - status
        - moneyTransfer
      properties:
        status:
          $ref: '#/components/schemas/ApiResponse'
        moneyTransfer:
          $ref: '#/components/schemas/MoneyTransfer'

    ApiCode:
      type: "string"
      enum:
        - FAILED
        - ACCOUNT_CREATED
        - ACCOUNTS_LISTED
        - MONEY_TRANSFERRED
    ApiResponse:
      type: "object"
      required:
        - code
      properties:
        code:
          $ref: '#/components/schemas/ApiCode'
    ApiErrorResponse:
      required:
        - status
        - message
      properties:
        status:
          $ref: '#/components/schemas/ApiResponse'
        message:
          type: "string"
